[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ment"
version = "0.0.1"
dependencies = [
    "numpy>=2.0.0",
    "scipy",
]
requires-python = ">=3.8"
readme = "README.md"
