[project]
name = "ment"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "matplotlib==3.8.4",
    "numpy<2.0.0",
    "psdist @ git+https://github.com/austin-hoover/psdist",
    "scipy",
    "tqdm",
]

[build-system]
requires = [
    "setuptools>=62",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["ment"]
